name: vy_date
description: A couple of simple utilities, Date and DatePeriod classes. Date is a wrapper around DateTime class.
  DatePeriod allows to manage periods
version: 1.0.1
homepage: https://github.com/giorgiofran/vy_date

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.4
  lints: ^2.0.0
