name: vy_date
description: A couple of simple utilities, Date and DatePeriod classes.
version: 0.3.0
# homepage: https://www.example.com
author: Giorgio <giorgiofran@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.1 <2.0.0'

dependencies:
  intl: ^0.15.7
  quiver: any

dev_dependencies:
  test: ^0.12.30
